import { toggleViewPanel } from './view-options';
import { expect, test } from '@playwright/test';
import { mkdir } from 'node:fs/promises';
import { resolve } from 'node:path';

test('discovers, creates, switches, and reconnects sessions while retaining drafts', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await page.goto('/');
  const compact = testInfo.project.name === 'chromium-mobile';
  const context = () => compact ? page.getByRole('dialog', { name: 'Context' }) : page.locator('#lab-context');
  const showContext = async () => {
    if (compact && !await context().isVisible()) await toggleViewPanel(page, 'Sidebar');
  };
  await expect(context().getByRole('region', { name: 'Discover sessions' })).toBeVisible();
  const discovery = () => context().getByRole('region', { name: 'Discover sessions' });
  await expect(discovery().locator('.lab-session-row').first()).toBeVisible();
  const existingTitle = await discovery().locator('.lab-session-row strong').first().innerText();
  await discovery().locator('.lab-session-row').first().click();
  await expect(page.getByTestId('prompt-input')).toBeEnabled();
  const originalAgent = new URL(page.url()).searchParams.get('agent');
  await page.getByTestId('prompt-input').fill('A draft to retain while switching sessions.');
  await showContext();
  await context().getByTestId('session-create').click();
  await expect(page.getByTestId('prompt-input')).toBeEnabled();
  await expect.poll(() => new URL(page.url()).searchParams.get('agent')).not.toBe(originalAgent);
  await page.getByTestId('prompt-input').fill('Hello from the independent workbench.');
  await page.getByTestId('prompt-input').press('Enter');
  await expect(page.locator('.agent-message-assistant').filter({ hasText: 'Recorded reply: Hello from the independent workbench.' })).toBeVisible();
  await showContext();
  const opened = () => context().getByRole('region', { name: 'Opened sessions' });
  await expect(opened().locator('.lab-session-row')).toHaveCount(2);
  await opened().getByRole('button').filter({ has: page.getByText(existingTitle, { exact: true }) }).click();
  await expect(page.getByTestId('prompt-input')).toBeEnabled();
  await expect(page.getByTestId('prompt-input')).toHaveValue('A draft to retain while switching sessions.');
  await showContext();
  await discovery().locator('.lab-session-row').first().click();
  if (compact) await expect(context()).toHaveCount(0);
  await expect(page.getByTestId('prompt-input')).toBeEnabled();
  await showContext();
  await expect(opened().locator('.lab-session-row')).toHaveCount(2);
  if (compact) await context().getByRole('button', { name: 'Close Context' }).click();
  await page.getByLabel('Connection details', { exact: true }).click();
  await page.getByRole('button', { name: 'Reconnect', exact: true }).click();
  await expect(page.getByTestId('prompt-input')).toBeEnabled();
  await expect(page.getByTestId('prompt-input')).toHaveValue('A draft to retain while switching sessions.');
  await page.getByRole('tab', { name: 'Trace' }).click();
  await expect(page.getByRole('heading', { name: 'Normalized Timeline trace' })).toBeVisible();
  await page.getByRole('tab', { name: 'Workbench' }).click();
  expect(errors).toEqual([]);
  const evidence = resolve('../../.tmp/evidence');
  await mkdir(evidence, { recursive: true });
  await page.screenshot({ path: `${evidence}/directory-${testInfo.project.name}.png`, fullPage: true });
  await showContext();
  await page.screenshot({ path: `${evidence}/directory-context-${testInfo.project.name}.png`, fullPage: true });
});

test('creates a temporary pairing key through the workbench', async ({ page }, testInfo) => {
  await page.goto('/');
  const context = testInfo.project.name === 'chromium-mobile' ? page.getByRole('dialog', { name: 'Context' }) : page.locator('#lab-context');
  await expect(context.getByLabel('Connected Host')).toHaveValue('local');
  await context.getByRole('button', { name: 'Pair DSH Host' }).click();
  const responsePromise = page.waitForResponse((response) => response.url().endsWith('/v1/remote/pairings') && response.request().method() === 'POST');
  await context.getByRole('button', { name: 'Generate pairing key' }).click();
  const response = await responsePromise;
  expect(response.ok()).toBe(true);
  const invitation = await response.json();
  await expect(context.getByLabel('DSH Host configuration')).toHaveValue(new RegExp(invitation.key));
  await expect(context.getByRole('button', { name: 'Copy configuration' })).toBeEnabled();
  await expect(context.getByText(/Key expires/)).toBeVisible();
});
