import { expect, test } from '@playwright/test';

for (const viewport of [{ width: 393, height: 852 }, { width: 320, height: 568 }, { width: 844, height: 390 }]) {
  test(`mobile sidebar keeps discovery and navigation reachable at ${viewport.width}`, async ({ page }, info) => {
    test.skip(!info.project.use.isMobile);
    await page.setViewportSize(viewport);
    await page.route('**/v1/favorites', route => route.fulfill({ json: { revision: 0, folders: [], stars: [] } }));
    await page.route('**/v1/remote/hosts/host/vscode-tunnel', route => route.fulfill({ json: { status: 'stopped', processAlive: false, revision: 0 } }));
    await page.route('**/v1/remote/hosts/host/previews', route => route.fulfill({ json: { revision: 1, registrations: [] } }));
    await page.goto('/e2e/fixtures/session-stars.html?sidebar=1');
    const tracking = page.getByRole('button', { name: 'Tracked sessions', exact: true });
    await expect(tracking).toBeVisible();
    await page.getByRole('button', { name: 'Open sessions', exact: true }).click();
    const rail = page.getByRole('dialog', { name: 'Context', exact: true });
    const scroll = rail.locator('.lab-sidebar-content');
    async function assertPanelWidth(panel: string) {
      const bounds = await scroll.evaluate(element => {
        element.scrollLeft = 1000;
        return { width: element.clientWidth, scrollWidth: element.scrollWidth, left: element.scrollLeft };
      });
      expect(bounds.scrollWidth, `${panel} must fit its own scrollport`).toBeLessThanOrEqual(bounds.width + 1);
      expect(bounds.left, `${panel} must not scroll horizontally`).toBe(0);
    }
    const discover = rail.getByRole('region', { name: 'Discover sessions' });
    await expect(discover.locator('.lab-session-row')).toHaveCount(24);
    await expect(tracking).toBeHidden();
    await assertPanelWidth('Sessions');
    await expect(rail.getByRole('button', { name: /Controller updates/ })).toBeHidden();
    await expect(rail.getByRole('region', { name: 'Host VS Code tunnel' })).toHaveCount(0);
    await expect(rail.getByRole('searchbox', { name: 'Find an execution environment' })).toBeHidden();
    if (viewport.height > 600) await expect(discover.locator('.lab-session-row').first()).toBeInViewport();
    await expect(page.getByRole('alert')).toHaveCount(0);
    await page.screenshot({ path: info.outputPath('sessions.png') });
    const footer = rail.getByRole('button', { name: 'New session', exact: true });
    const before = await footer.boundingBox();
    await scroll.evaluate(element => { element.scrollTop = element.scrollHeight; });
    await expect(discover.locator('.lab-session-row').last()).toBeInViewport();
    expect(await footer.boundingBox()).toEqual(before);
    const scrollBox = (await scroll.boundingBox())!;
    expect(scrollBox.y + scrollBox.height).toBeLessThanOrEqual(before!.y);
    await expect(rail.getByRole('navigation', { name: 'Sidebar sections' })).toBeInViewport();
    await rail.getByRole('button', { name: 'Settings', exact: true }).click();
    expect(await scroll.evaluate(element => element.scrollTop)).toBe(0);
    await assertPanelWidth('Settings');
    const updates = rail.getByRole('button', { name: /Controller updates/ });
    await expect(updates).toBeVisible();
    await updates.click();
    await assertPanelWidth('Settings with Controller updates');
    const vscode = rail.getByRole('region', { name: 'Host VS Code tunnel' });
    await expect(vscode).toBeVisible();
    const checkbox = vscode.getByRole('checkbox');
    await checkbox.check();
    expect((await checkbox.boundingBox())!.height).toBeLessThanOrEqual(22);
    await expect(vscode.getByRole('button', { name: 'Start tunnel' })).toBeEnabled();
    await page.screenshot({ path: info.outputPath('settings.png') });
    await rail.getByRole('button', { name: 'Favorites', exact: true }).click();
    await assertPanelWidth('Favorites');
    await expect(rail.getByRole('button', { name: /Controller updates/ })).toBeHidden();
    await rail.getByRole('button', { name: 'Settings', exact: true }).click();
    await expect(updates).toHaveAttribute('aria-expanded', 'true');
    await rail.getByRole('button', { name: 'Sessions', exact: true }).click();
    expect(await scroll.evaluate(element => element.scrollTop)).toBe(0);
    await rail.locator('.lab-host-disclosure > summary').click();
    await assertPanelWidth('Sessions with Host details');
    await rail.getByRole('searchbox', { name: 'Find an execution environment' }).fill('mac zsh');
    await expect(rail.getByRole('status').filter({ hasText: '1 matching Hosts' })).toBeVisible();
    await rail.locator('.lab-host-disclosure > summary').click();
    await rail.locator('.lab-rail-close').focus();
    await page.keyboard.press('Shift+Tab');
    await expect(footer).toBeFocused();
    await page.keyboard.press('Tab');
    await expect(rail.locator('.lab-rail-close')).toBeFocused();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.keyboard.press('Escape');
    await expect(tracking).toBeVisible();
    await expect(page.getByRole('button', { name: 'Open sessions', exact: true })).toBeFocused();
  });
}

test('manages tracking from the sidebar favorites filter without row close buttons', async ({ page }, info) => {
  if (info.project.use.isMobile) await page.setViewportSize({ width: 320, height: 740 });
  const star = { hostId: 'host', providerId: 'recorded', nativeSessionId: 'tracked', title: 'Research notes', starredAt: 1,
    favoriteId: 'tracked', folderId: 'work', order: 0, available: true, online: true, hostName: 'Work Mac' };
  const other = { ...star, nativeSessionId: 'other', favoriteId: 'other', order: 1 };
  const orphan = { ...star, nativeSessionId: 'removed', favoriteId: 'removed' };
  let stars = [star, other];
  await page.addInitScript(({ star, orphan }) => {
    localStorage.setItem(`agent-remote-tracking:${location.origin}/u/alice/`, JSON.stringify([star, orphan]));
  }, { star, orphan });
  await page.route('**/v1/session-migrations', route => route.fulfill({ json: { migrations: [] } }));
  await page.route('**/v1/favorites', async route => {
    const body = route.request().method() === 'POST' ? route.request().postDataJSON() : undefined;
    if (body?.type === 'remove-session') stars = stars.filter(s => s.nativeSessionId !== body.session.nativeSessionId);
    await route.fulfill({ json: { revision: 1, folders: [{ id: 'work', parentId: null, title: 'Work', order: 0 }], stars } });
  });
  await page.route('**/v1/remote/hosts/host/attach', route => route.fulfill({ json: { agentId: 'tracked-agent' } }));
  await page.route('**/v1/remote/hosts/host/vscode-tunnel', route => route.fulfill({ json: { status: 'stopped', processAlive: false, revision: 0 } }));
  await page.route('**/v1/remote/hosts/host/previews', route => route.fulfill({ json: { revision: 1, registrations: [] } }));
  await page.goto('/e2e/fixtures/session-stars.html?sidebar=1');
  const saved = () => page.evaluate(() => JSON.parse(localStorage.getItem(`agent-remote-tracking:${location.origin}/u/alice/`) ?? '[]').map((s: { nativeSessionId: string }) => s.nativeSessionId));
  await expect.poll(saved).toEqual(['tracked']);
  await page.getByRole('button', { name: 'Tracked sessions', exact: true }).click();
  await expect(page.locator('.lab-tracking-floating [aria-label^="Untrack "]')).toHaveCount(0);
  await expect(page.locator('.lab-tracking-floating .lab-session-row')).toHaveCount(1);
  expect((await page.locator('.lab-tracking-floating .lab-session-row').boundingBox())!.width).toBeGreaterThan(150);
  await page.getByRole('button', { name: 'Close Tracked sessions', exact: true }).click();
  if (info.project.use.isMobile) await page.getByRole('button', { name: 'Open sessions', exact: true }).click();
  const rail = page.locator('#lab-context');
  await rail.getByRole('button', { name: 'Favorites', exact: true }).click();
  const filter = rail.getByRole('button', { name: 'Filter tracked favorites', exact: true });
  const all = rail.getByRole('button', { name: 'Show all favorites', exact: true });
  await expect(all).toHaveText('2 favorites');
  await expect(all).toHaveAttribute('aria-pressed', 'true');
  await expect(filter).toHaveText('1 tracked');
  const toolbar = rail.locator('.lab-favorites-toolbar');
  expect(await toolbar.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await filter.click();
  await expect(filter).toHaveAttribute('aria-pressed', 'true');
  await expect(all).toHaveAttribute('aria-pressed', 'false');
  await expect(rail.locator('[role="treeitem"]')).toHaveCount(1);
  await expect(rail.locator('[data-favorite-id="tracked"]')).toBeVisible();
  const nav = rail.getByRole('navigation', { name: 'Sidebar sections' });
  expect(await nav.evaluate(el => el.scrollWidth <= el.clientWidth + 1)).toBe(true);
  await page.screenshot({ path: info.outputPath('tracked-favorites.png'), animations: 'disabled' });
  await rail.getByRole('button', { name: 'Actions for Research notes', exact: true }).click();
  await page.locator('.lab-favorite-menu').getByRole('button', { name: 'Untrack', exact: true }).click();
  await expect(rail.getByText('No tracked favorites.', { exact: false })).toBeVisible();
  await expect.poll(saved).toEqual([]);
  await expect(filter).toHaveText('0 tracked');
  await all.click();
  await expect(filter).toHaveAttribute('aria-pressed', 'false');
  await rail.getByRole('button', { name: 'Work', exact: true }).click();
  await expect(rail.locator('[data-favorite-id="tracked"]')).toBeVisible();
  await expect(rail.locator('[data-favorite-id="other"]')).toBeVisible();
  await rail.locator('[data-favorite-id="tracked"]').getByRole('button', { name: 'Actions for Research notes' }).click();
  await page.locator('.lab-favorite-menu').getByRole('button', { name: 'Track', exact: true }).click();
  await filter.click();
  await rail.getByRole('button', { name: 'Actions for Research notes', exact: true }).click();
  await page.locator('.lab-favorite-menu').getByRole('button', { name: 'Remove favorite', exact: true }).click();
  await expect.poll(saved).toEqual([]);
  await expect(filter).toHaveText('0 tracked');
  await all.click();
  await expect(rail.locator('[data-favorite-id="other"]')).toBeVisible();
  await expect(rail.locator('[data-favorite-id="tracked"]')).toHaveCount(0);
});
