import { expect, test, devices } from '@playwright/test';
import { showNewSession } from './session-navigation';
import { sessionLinkFixture } from './session-link-fixture';

test('a clean mobile browser finds desktop Side and Ask from their source without creating or replaying them', async ({ browser, page }, testInfo) => {
  test.skip(testInfo.project.name !== 'chromium-desktop', 'Uses separate desktop and mobile contexts.');
  const f = await sessionLinkFixture();
  const mobile = await browser.newContext({ ...devices['iPhone 13'], baseURL: f.url });
  try {
    await page.goto(f.url + '/auth/login');
    await page.getByRole('link', { name: 'Sign in as alice' }).click();
    await page.getByLabel('Connected Host').selectOption(f.hostId);
    await showNewSession(page);
    await expect(page.getByTestId('session-create')).toBeEnabled();
    await page.getByTestId('session-create').click();
    const primary = page.locator('.lab-primary-conversation');
    const input = primary.getByTestId('prompt-input');
    await expect(input).toBeEnabled();
    const sourceUrl = page.url();
    await input.fill('/ask Desktop question'); await input.press('Enter');
    const ask = page.getByRole('dialog', { name: 'Ask', exact: true });
    await expect(ask.locator('.agent-message-assistant').last()).toContainText('Desktop question');
    const askMessages = await ask.locator('.agent-message-user').count();
    await ask.getByRole('button', { name: 'Minimize Ask', exact: true }).click();
    await input.fill('/side Desktop side question'); await input.press('Enter');
    const side = page.getByRole('complementary', { name: 'Side conversation' });
    await expect(side.locator('.agent-message-assistant').last()).toContainText('Desktop side question');
    const sideMessages = await side.locator('.agent-message-user').count();
    const phone = await mobile.newPage();
    const writes: string[] = [];
    phone.on('request', request => { if (request.method() === 'POST' && /\/create$|\/operations$/.test(new URL(request.url()).pathname)) writes.push(request.url()); });
    await phone.goto(sourceUrl);
    await phone.getByRole('link', { name: 'Sign in through gateway' }).click();
    await phone.getByRole('link', { name: 'Sign in as alice' }).click();
    const phonePrimary = phone.locator('.lab-primary-conversation');
    const entries = phonePrimary.getByRole('navigation', { name: 'Forked sessions' }).getByRole('button');
    await expect(entries).toHaveCount(1);
    await expect(phone.getByRole('button', { name: 'Ask about this session', exact: true })).toBeVisible();
    await entries.click();
    const phoneSide = phone.getByRole('complementary', { name: 'Side conversation' });
    await expect(phoneSide.locator('.agent-message-assistant').last()).toContainText('Desktop side question');
    await expect(phoneSide.locator('.agent-message-user')).toHaveCount(sideMessages);
    await expect(phoneSide.getByTestId('prompt-input')).toBeEnabled();
    expect(await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await phone.screenshot({ animations: 'disabled', path: testInfo.outputPath('mobile-shared-side.png') });
    await phone.goto(sourceUrl);
    await phone.getByRole('button', { name: 'Ask about this session', exact: true }).click();
    const phoneAsk = phone.getByRole('dialog', { name: 'Ask', exact: true });
    await expect(phoneAsk.locator('.agent-message-assistant').last()).toContainText('Desktop question');
    await phone.screenshot({ animations: 'disabled', path: testInfo.outputPath('mobile-shared-ask.png') });
    await expect(phoneAsk.locator('.agent-message-user')).toHaveCount(askMessages);
    expect(writes).toEqual([]);
  } finally { await mobile.close(); await f.close(); }
});
