import { expect, test } from '@playwright/test';
import { toggleViewPanel } from './view-options';
import { showNewSession } from './session-navigation';

test('inspects a live tool and returns to a stable conversation anchor', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/e2e/fixtures/trace-inspection.html');
  const prompt = page.getByTestId('prompt-input');
  await prompt.fill('Keep this draft');
  const viewport = page.getByTestId('timeline');
  const entry = viewport.locator('[data-entry-key="epoch-1:recorded:12:test-call"]');
  await viewport.hover();
  await page.mouse.wheel(0, -3000);
  await entry.scrollIntoViewIfNeeded();
  await entry.hover();
  await entry.getByRole('button', { name: 'Inspect event #12 in Trace' }).click();
  const details = page.getByRole('region', { name: 'Trace entry details' });
  await expect(details).toBeVisible();
  await expect(details).toContainText('pnpm test --testTimeout=10000');
  await expect(details).toContainText('No result received yet');
  await page.getByRole('button', { name: 'Complete tool', exact: true }).click();
  await expect(details).toContainText('All tests passed.');
  await expect(details).toContainText('1200 ms');
  await expect(page.locator('[data-trace-entry-key][aria-current="true"]')).toHaveAttribute('data-trace-entry-key', 'epoch-1:recorded:12:test-call');
  if (!await page.getByRole('tab', { name: 'Trace', exact: true }).isVisible()) await toggleViewPanel(page, 'Header');
  await details.evaluate(element => { element.scrollTop = 160; });
  const detailTop = await details.evaluate(element => element.scrollTop);
  await page.getByRole('tab', { name: 'Workbench', exact: true }).click();
  await page.getByRole('tab', { name: 'Trace', exact: true }).click();
  await expect.poll(() => details.evaluate(element => element.scrollTop)).toBe(detailTop);
  await expect.poll(() => page.locator('.lab-trace-browser').evaluate(element => element.scrollWidth - element.clientWidth)).toBeLessThanOrEqual(1);
  await page.screenshot({ path: testInfo.outputPath('trace-details.png') });
  await details.getByRole('button', { name: 'Show in Conversation' }).click();
  await expect(entry).toHaveAttribute('data-inspected', 'true');
  await expect(prompt).toHaveValue('Keep this draft');
  const anchor = await entry.evaluate(element => element.getBoundingClientRect().top);
  const top = await viewport.evaluate(element => element.scrollTop);
  await page.getByRole('button', { name: 'Append event', exact: true }).click();
  await expect.poll(() => viewport.evaluate(element => element.scrollTop)).toBe(top);
  expect(Math.abs(await entry.evaluate(element => element.getBoundingClientRect().top) - anchor)).toBeLessThanOrEqual(1);
  await viewport.hover();
  await page.mouse.wheel(0, 160);
  await expect.poll(() => viewport.evaluate(element => element.scrollTop)).not.toBe(top);
  const readingTop = await viewport.evaluate(element => element.scrollTop);
  await page.getByRole('tab', { name: 'Trace', exact: true }).click();
  await page.getByRole('tab', { name: 'Workbench', exact: true }).click();
  await expect.poll(() => viewport.evaluate(element => element.scrollTop)).toBe(readingTop);
  expect(errors).toEqual([]);
});

test('returns to the root conversation from trace while nested side sessions are expanded', async ({ page }) => {
  await page.goto('/');
  await showNewSession(page);
  await page.getByTestId('session-create').click();
  const primary = page.locator('.lab-primary-conversation');
  await expect(primary.getByTestId('prompt-input')).toBeEnabled();
  await primary.getByTestId('prompt-input').fill('Find the cobalt orchard answer.');
  await primary.getByTestId('prompt-input').press('Enter');
  await expect(primary.locator('.agent-message-assistant').last()).toContainText('cobalt orchard');
  let pane = primary;
  for (const text of ['First trace branch', 'Second trace branch']) {
    await pane.getByTestId('prompt-input').fill(`/side ${text}`);
    await pane.getByTestId('prompt-input').press('Enter');
    pane = page.locator('.lab-side-conversation').filter({ has: page.locator('.agent-message-user').filter({ hasText: text }) });
    await expect(pane.locator('.agent-message-assistant').last()).toContainText(text);
  }
  await expect(primary).toBeHidden();
  if (!await page.getByRole('tab', { name: 'Trace', exact: true }).isVisible()) await toggleViewPanel(page, 'Header');
  await page.getByRole('tab', { name: 'Trace', exact: true }).click();
  const row = page.locator('[data-trace-entry-key]').filter({ hasText: 'cobalt orchard' }).last();
  const key = await row.getAttribute('data-trace-entry-key');
  await row.click();
  await page.getByRole('button', { name: 'Show in Conversation', exact: true }).click();
  await expect(primary).toBeVisible();
  const selected = primary.locator('[data-inspected="true"]');
  await expect(selected).toHaveAttribute('data-entry-key', key!);
  await expect(selected).toBeFocused();
  await expect(selected).toBeInViewport();
});

test('filters trace events, restores list focus, and resets inspection on an epoch change', async ({ page }) => {
  await page.goto('/e2e/fixtures/trace-inspection.html');
  await expect(page.getByTestId('prompt-input')).toBeEnabled();
  if (!await page.getByRole('tab', { name: 'Trace', exact: true }).isVisible()) await toggleViewPanel(page, 'Header');
  await page.getByRole('tab', { name: 'Trace', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Search trace' }).fill('pnpm test');
  const rows = page.locator('[data-trace-entry-key]');
  await expect(rows).toHaveCount(1);
  await rows.first().click();
  const details = page.getByRole('region', { name: 'Trace entry details' });
  await expect(details).toBeFocused();
  await details.press('Escape');
  await expect(rows.first()).toBeFocused();
  await rows.first().press('Enter');
  await expect(details).toContainText('/workspace/example');
  await page.getByRole('button', { name: 'Replace timeline', exact: true }).click();
  await expect(page.locator('[data-trace-entry-key][aria-current="true"]')).toHaveCount(0);
  await expect(page.getByRole('searchbox', { name: 'Search trace' })).toHaveValue('');
});
