import {mkdtemp, writeFile, rm} from 'node:fs/promises';
import {homedir} from 'node:os';
import {join} from 'node:path';
import {expect, test, type WebSocketRoute} from '@playwright/test';
import {fixture, reply} from '../../agent-provider-copilot/tests/native-fixture.js';
import {createDebuggerServer} from '../dist/server.js';

test('mobile Copilot view keeps approvals through reconnect and controls native permissions', async ({page, context}, info) => {
 test.setTimeout(45000);
 await page.setViewportSize({width: 402, height: 874});
 const outside = await mkdtemp(join(homedir(), '.arc-approval-browser-'));
 const file = join(outside, 'source.txt'); await writeFile(file, 'BROWSER_APPROVAL_MARKER');
 const f = await fixture((body, res, index) => reply(res, body, index <= 2 ? {name: 'view', arguments: {path: file}} : index === 4 ? {name: 'bash', arguments: {command: 'echo BROWSER_SHELL', description: 'Print a test marker'}} : index === 3 ? 'BROWSER_READS_COMPLETE' : 'BROWSER_SHELL_COMPLETE'));
 const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
 const server = await createDebuggerServer({adapter: f.provider, config: {cwd: f.cwd, model: 'gpt-4.1'}});
 try {
  const sockets: WebSocketRoute[] = [];
  await page.routeWebSocket('**', socket => {socket.connectToServer(); sockets.push(socket);});
  await page.goto(server.url);
  const input = page.getByRole('textbox', {name: 'Message', exact: true});
  await expect(input).toBeEditable(); await input.fill('Read the fixture file twice.');
  await page.getByRole('button', {name: 'Send message', exact: true}).click();
  const pending = page.getByRole('complementary', {name: 'Pending interactions'});
  await expect(pending).toContainText('Path access');
  await expect(pending).not.toContainText('toolCallId');
  await expect(pending).not.toContainText('permissionRequest');
  await context.setOffline(true);
  for (const socket of sockets) socket.close({code: 1001, reason: 'Test connection interruption'});
  await page.evaluate(() => window.dispatchEvent(new Event('offline')));
  await expect(pending).toContainText('Waiting for connection to respond.');
  await expect(pending).toContainText('Path access');
  await expect(pending).not.toContainText('Interaction unavailable');
  await expect(pending.getByRole('button', {name: 'Allow for session', exact: true})).toBeDisabled();
  await context.setOffline(false); await page.evaluate(() => window.dispatchEvent(new Event('online')));
  await expect(pending.getByRole('button', {name: 'Allow for session', exact: true})).toBeEnabled({timeout: 15000});
  await pending.getByRole('button', {name: 'Allow for session', exact: true}).click();
  await expect(pending).toContainText('Allows read tools for the rest of this session');
  await pending.getByRole('button', {name: 'Allow for session', exact: true}).click();
  await expect(page.getByText('BROWSER_READS_COMPLETE', {exact: true})).toBeVisible({timeout: 15000});
  await expect(page.getByText('Allowed for session', {exact: true})).toHaveCount(2);
  await expect(pending).toHaveCount(0);
  await page.getByTestId('session-permissions-button').click();
  const select = page.getByTestId('session-setting-tool_approval_mode');
  await expect(select).toBeEnabled(); await expect(select).toHaveValue('ask');
  await select.selectOption('allow'); await expect(select).toHaveValue('allow');
  await expect(page.getByTestId('session-permissions-button')).toContainText('Allow tools');
  await select.selectOption('ask'); await expect(select).toHaveValue('ask');
  await page.screenshot({path: info.outputPath('copilot-mobile-permissions.png'), fullPage: true});
  await page.getByRole('button', {name: 'Close session controls', exact: true}).click();
  await input.fill('Run the shell marker.');
  await page.getByRole('button', {name: 'Send message', exact: true}).click();
  await expect(pending.getByRole('button', {name: 'Allow once', exact: true})).toBeEnabled();
  await expect(pending.locator('pre[aria-label="Command"]')).toHaveCount(1);
  await expect(pending.locator('pre[aria-label="Command"]')).toHaveText('echo BROWSER_SHELL');
  await expect(pending).not.toContainText('fullCommandText');
  await page.screenshot({path: info.outputPath('copilot-mobile-shell-approval.png'), fullPage: true});
  await pending.getByRole('button', {name: 'Allow once', exact: true}).click();
  await expect(page.getByText('BROWSER_SHELL_COMPLETE', {exact: true})).toBeVisible({timeout: 15000});
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  expect(errors).toEqual([]);
 } finally {await context.setOffline(false); await server.close(); await f.close(); await rm(outside, {recursive: true, force: true});}
});
