import { afterEach, expect, it, vi } from 'vitest';
import { RemoteActivityClient, type RemoteActivityState } from './remote-activity-client.js';
import type { RemoteAgentTransport, RemoteTransportListener } from './transport.js';
afterEach(() => vi.useRealTimers());
it('negotiates activity only, reconnects without replaying content, and releases its socket', async () => {
  vi.useFakeTimers();
  let listener!: RemoteTransportListener;
  const send = vi.fn(), close = vi.fn(), fetchSnapshot = vi.fn(), fetchTimeline = vi.fn();
  const connect = vi.fn((_id, next) => { listener = next; return { send, close }; });
  const transport: RemoteAgentTransport = { connect, fetchSnapshot, fetchTimeline, onDiagnostic: () => () => {}, onProtocolMessage: () => () => {} };
  const values: RemoteActivityState[] = [];
  const client = new RemoteActivityClient('agent', transport, state => values.push(state));
  client.start(); listener.onOpen();
  expect(send.mock.calls).toEqual([[{ protocolVersion: '1.4.0', type: 'negotiate', observation: 'activity' }]]);
  listener.onMessage({ protocolVersion: '1.4.0', type: 'agent_activity', payload: { agentId: 'agent', status: 'running' } });
  expect(values.at(-1)).toEqual({ connection: 'ready', activity: 'running' });
  listener.onDisconnect();
  expect(values.at(-1)).toEqual({ connection: 'disconnected' });
  await vi.advanceTimersByTimeAsync(1000);
  listener.onOpen();
  expect(connect).toHaveBeenCalledTimes(2);
  expect(fetchSnapshot).not.toHaveBeenCalled(); expect(fetchTimeline).not.toHaveBeenCalled();
  client.stop();
  await vi.advanceTimersByTimeAsync(60000);
  expect(connect).toHaveBeenCalledTimes(2);
  expect(close).toHaveBeenCalledTimes(2);
});
it('shows an unsupported Host without falling back to content or retrying forever', async () => {
  vi.useFakeTimers();
  let listener!: RemoteTransportListener;
  const connect = vi.fn((_id, next) => { listener = next; return { send: vi.fn(), close: vi.fn() }; });
  const values: RemoteActivityState[] = [];
  const client = new RemoteActivityClient('agent', { connect } as unknown as RemoteAgentTransport, state => values.push(state));
  client.start(); listener.onOpen();
  listener.onMessage({ protocolVersion: '1.4.0', type: 'protocol_error', payload: { code: 'invalid_shape', message: 'Unknown field', recoverable: false } });
  expect(values.at(-1)?.error).toContain('Update the Controller');
  await vi.advanceTimersByTimeAsync(60000);
  expect(connect).toHaveBeenCalledOnce();
  client.stop();
});
